AWSTemplateFormatVersion: "2010-09-09"
Description: "Aurora DB - Fix Version Error and Update Security Group"

Resources:
  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Secure Subnet Group for DevSecOps"
      SubnetIds: 
        - !ImportValue DevSecOps-Private-Subnet-A
        - !ImportValue DevSecOps-Private-Subnet-B
      Tags:
        - Key: "Name"
          Value: "devsecops-db-subnet-group"

  AuroraDBCluster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      Engine: "aurora-mysql"
      # EngineVersion সরিয়ে দিলাম যাতে ভার্সন নিয়ে কোনো ক্যাচাল না হয়
      MasterUsername: "{{resolve:secretsmanager:findmyproject/db_creds:SecretString:username}}"
      MasterUserPassword: "{{resolve:secretsmanager:findmyproject/db_creds:SecretString:password}}"
      DBSubnetGroupName: !Ref "DBSubnetGroup"
      VpcSecurityGroupIds:
        - !ImportValue DBSecurityGroupID # এটিই আমাদের মেইন লক্ষ্য
      StorageEncrypted: true
      DeletionProtection: false

  AuroraDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref "AuroraDBCluster"
      DBInstanceClass: "db.t3.medium"
      Engine: "aurora-mysql"
      DBSubnetGroupName: !Ref "DBSubnetGroup"