AWSTemplateFormatVersion: "2010-09-09"
Description: Internet Gateway for DevSecOps Project

Resources:

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: devsecops-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: vpc-0590b10eae8df4a81
      InternetGatewayId: !Ref InternetGateway