AWSTemplateFormatVersion: "2010-09-09"
Description: Internet Gateway + Public Routing (Dual Stack, Multi-AZ, Final) - Updated with Private Subnet Routing

Resources:

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: devsecops-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !ImportValue DevSecOps-VPC-ID
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue DevSecOps-VPC-ID
      Tags:
        - Key: Name
          Value: devsecops-public-rt

  PublicRouteIPv4:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicRouteIPv6:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationIpv6CidrBlock: ::/0
      GatewayId: !Ref InternetGateway

  PublicSubnetAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: PublicRouteIPv4
    Properties:
      SubnetId: !ImportValue DevSecOps-Public-Subnet-A
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: PublicRouteIPv4
    Properties:
      SubnetId: !ImportValue DevSecOps-Public-Subnet-B
      RouteTableId: !Ref PublicRouteTable

  
  PrivateSubnetAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !ImportValue DevSecOps-Private-Subnet-A
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !ImportValue DevSecOps-Private-Subnet-B
      RouteTableId: !Ref PublicRouteTable

Outputs:

  DevSecOpsIGW:   
    Value: !Ref InternetGateway
    Export:
      Name: DevSecOps-IGW

  DevSecOpsPublicRouteTable:   
    Value: !Ref PublicRouteTable
    Export:
      Name: DevSecOps-Public-RouteTable