AWSTemplateFormatVersion: "2010-09-09"
Description: Subnets for DevSecOps Project

Resources:

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-0590b10eae8df4a81
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-south-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: public-subnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-0590b10eae8df4a81
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-south-1a
      Tags:
        - Key: Name
          Value: private-subnet