apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::800557028391:role/devsecops-eks-iam-EKSNodeRole-uVP1v1fbE1tB
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::800557028391:role/codebuild-devsecops-build-service-role2
      groups:
      - system:masters
      username: codebuild
  mapUsers: |
    []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system