AWSTemplateFormatVersion: "2010-09-09"
Description: EKS Managed Node Group (Production Grade 1.33)

Resources:

  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !ImportValue DevSecOps-EKS-Cluster
      NodegroupName: devsecops-node-group-v1-33 

      
      Version: "1.33"

      NodeRole: !ImportValue DevSecOps-EKS-Node-Role

      Subnets:
        - !ImportValue DevSecOps-Private-Subnet-A
        - !ImportValue DevSecOps-Private-Subnet-B

      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3

      InstanceTypes:
        - t3.medium

      
      AmiType: AL2023_x86_64_STANDARD

      DiskSize: 20

      CapacityType: ON_DEMAND

      UpdateConfig:
        MaxUnavailable: 1

      Labels:
        environment: production
        nodegroup: devsecops
        kubernetes-version: "1.33"

      Tags:
        Name: devsecops-node-group

Outputs:

  NodeGroupName:
    Description: EKS Node Group Name
    Value: !Ref EKSNodeGroup