AWSTemplateFormatVersion: "2010-09-09"
Description: Security Group for DevSecOps Project (IPv4 + IPv6, Production Ready)

Parameters:
  MyIPv4:
    Type: String
    Default: 49.37.45.51/32
    Description: Your IPv4 address for SSH

  MyIPv6:
    Type: String
    Default: 2405:201:800a:4813:1a8d:2c9:369d:d668/128
    Description: Your IPv6 address for SSH

Resources:

  DevSecOpsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP/HTTPS public and restricted SSH
      VpcId: !ImportValue DevSecOps-VPC-ID

      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIpv6: ::/0

        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIpv6: ::/0

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIPv4

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIpv6: !Ref MyIPv6

      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

        - IpProtocol: -1
          CidrIpv6: ::/0

      Tags:
        - Key: Name
          Value: devsecops-sg

Outputs:
  SecurityGroupId:
    Value: !Ref DevSecOpsSecurityGroup
    Export:
      Name: DevSecOps-SG